### PR TITLE
Fix(Login): Login fixed, authentication done, works on phone.

### LINKED ISSUE #134: Fix Login Screen
**Description:** 
Stop the no credentials error from happening and have the login working on the APK.

**Criteria:**
- [x] Possible to enter inside the app with Google authentication.
- [x] Smooth login/logout flow.
- [x] Persistance when logging in (no need to log in each time).

### PR DESCRIPTION
**Pull request by Adessrrrr**
## Summary

This PR stabilizes the entire Google authentication flow, fixes navigation issues after login, removes all “no credentials available” / “reauth failed” errors, and rewrites the login architecture using a proper MVVM structure. The login screen, ViewModel, and MainActivity were refactored for correctness, clarity, and testability.
Other methods from the Google API were used, giving better success this time.

## What’s in this PR

- Full rewrite of LoginViewModel (state-driven, testable, injected credential provider).
- Updated LoginScreen using onLoggedIn callback and predictable navigation.
- Proper integration of GetSignInWithGoogleOption + Credential Manager API.
- Removal of direct FirebaseAuth usage inside UI.
- Simplified MainActivity (clean AuthStateListener + stable navigation).
- Added testable credentialProvider abstraction.
- Fixed login for all account types (personal / enterprise / school).
- Updated and corrected unit tests and E2E tests.

## Implementation Notes

- The ViewModel now handles all success/failure/exception branches cleanly.
- Navigation is no longer triggered at multiple layers; MainActivity owns the flow.
- dispatchers are controlled for deterministic unit testing.
- No Firestore schema or API changes.

## Testing
LoginViewModelTest that covers nearly all the cases.
FirebaseAuthRepository and GoogleAuthHelper also included in the tests.

## Screenshots / Demos
image
image

## Checklist

- [ ] Possible to enter inside the app with Google authentication.
- [ ] Smooth login/logout flow.
- [ ] Persistance when logging in (no need to log in each time).

## Notes
AI assistance (LLM) was used while implementing and/or refactoring the following files:

LoginViewModel.kt
LoginScreen.kt
MainActivity.kt
FirebaseAuthRepository.kt
GoogleAuthHelper.kt
LoginViewModelTest.kt
E2ELoginFlowTest.kt
MainDispatcherRule.kt

It was also used to help for this PR.

## Issue Reference
Closes #134

### CODE REVIEW

File: app/src/main/java/com/android/sample/ui/login/LoginViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+            .onFailure { e ->
+              _state.update {
+                it.copy(loading = false, user = null, error = e.message ?: "Login failed")
+              }
+            }
+      } catch (e: Exception) {
+        // IMPORTANT: this is the branch ton test essaie de vérifier
+        _state.update {
+          it.copy(
+              loading = false, user = null, error = e.message ?: "Unexpected error during login")
```
Comment (KenzaHassayoune) [inline app/src/main/java/com/android/sample/ui/login/LoginViewModel.kt]: Avoid hardcoded strings.

File: app/src/main/java/com/android/sample/ui/login/LoginViewModel.kt [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        val credential = credentialProvider(context, credentialManager)
+        val result = repo.loginWithGoogle(credential)
+
+        result
+            .onSuccess { user ->
+              _state.update { it.copy(loading = false, user = user, error = null) }
+            }
+            .onFailure { e ->
+              _state.update {
+                it.copy(loading = false, user = null, error = e.message ?: "Login failed")
```
Comment (KenzaHassayoune) [inline app/src/main/java/com/android/sample/ui/login/LoginViewModel.kt]: avoid hardcoded strings.

File: app/src/main/java/com/android/sample/ui/login/LoginScreen.kt [hunk 3]
```diff
@@ -15,121 +14,60 @@ import androidx.compose.ui.graphics.Brush
...
+              enabled = !state.loading,
+              colors = ButtonDefaults.buttonColors(containerColor = Color.White)) {
                 Image(
                     painter = painterResource(id = R.drawable.ic_google),
                     contentDescription = "Google icon",
                     modifier = Modifier.size(18.dp))
                 Spacer(Modifier.width(8.dp))
-                Text(if (loading) "Connexion..." else "Continuer avec Google", color = Color.Black)
+                Text(
+                    if (state.loading) "Connexion..." else "Continue with google",
```
Comment (KenzaHassayoune) [inline app/src/main/java/com/android/sample/ui/login/LoginScreen.kt]: avoid hardcoded strings.

File: app/src/main/java/com/android/sample/ui/login/FirebaseAuthRepository.kt [hunk 4]
```diff
@@ -7,22 +7,20 @@ import com.google.firebase.auth.FirebaseAuth
...
           credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
         val idToken = GoogleAuthHelper.fromBundle(credential.data).idToken
         val firebaseCred = GoogleAuthHelper.toFirebaseCredential(idToken)
         val user = auth.signInWithCredential(firebaseCred).await().user
         if (user != null) Result.success(user)
-        else Result.failure(IllegalStateException("Utilisateur introuvable après connexion."))
+        else Result.failure(IllegalStateException("No user after connexion"))
       } else {
-        Result.failure(IllegalArgumentException("Type de credential non supporté."))
+        Result.failure(IllegalArgumentException("Credential not supported"))
```
Comment (KenzaHassayoune) [inline app/src/main/java/com/android/sample/ui/login/FirebaseAuthRepository.kt]: Avoid hardcoded strings.

**Review by KenzaHassayoune — COMMENTED** [review]
Great work on enhancing the logic of login and authentication, respecting the MVVM model.
Just avoid the hardcoded strings to be able to merge it.

**Review by KenzaHassayoune — CHANGES_REQUESTED** [review]
Great work on enhancing the logic of login and authentication, respecting the MVVM model.
Just avoid the hardcoded strings to be able to merge it.

**Review by KenzaHassayoune — APPROVED** [review]
Good work!
