### PR TITLE
feature(schedule): enhance the schedule and fix bugs

### LINKED ISSUE #266: Improve Schedule feature reliability & academic correctness
- [x] Fix Week view showing empty or duplicated data
- [x] Fix Month view and display “Most important this month” events
- [x] Import exams from ICS and classify correctly (midterm / final)
- [x] Prevent exam duplication on timetable re-import
- [x] Fix class end times (support multi-hour classes from ICS)
- [x] Implement academic calendar logic (teaching / break / revision / exams)
- [x] Hide classes outside teaching weeks

### PR DESCRIPTION
**Pull request by KenzaHassayoune**
## Summary:

This PR stabilizes and completes the Schedule feature by fixing data consistency issues, improving academic correctness, and making Day / Week / Month views meaningful and reliable.

Initially, Week and Month views appeared empty or inconsistent due to missing event semantics, incorrect ICS handling, duplicated imports, inaccurate class durations, and lack of academic-calendar logic. This PR introduces a clear separation of concerns between classes, exams, tasks, and academic phases, ensuring the schedule behaves correctly across all views.

## What problem are we solving?

- Week and Month views showed no useful or duplicated data
- Exams present in ICS files were ignored or misclassified
- Re-importing a timetable caused exam duplication
- Classes appeared during revision and exam periods
- Class end times were incorrectly truncated to 1 hour
- Academic breaks were not respected due to missing holiday data

### Functional changes :
- Unified schedule data model : Recurring classes stored in PlannerRepository; Exams and tasks handled as ScheduleEvents
- Correct ICS exam import : Exams parsed from ICS and stored as high-priority events; Correct mapping to EXAM_FINAL / EXAM_MIDTERM
- Correct class duration handling: Class end times now respect ICS DTEND / DURATION and Multi-hour classes (e.g. 10:00–12:00) are displayed correctly
- Academic calendar logic (EPFL Fall semester) : Semester start: 08/09/2025; Mid-semester break after week 6; Teaching, break, revision, and exam phases computed deterministically
- Class suppression outside teaching weeks: Classes shown only during teaching weeks; No classes during break, revision, or exams
- Month view improvements: “Most important this month” reliably shows exams
- Bug fixes: Removed duplicate exam entries; Fixed incorrect use of stable IDs as titles; Fixed off-by-one academic week calculation

## Schema / API changes:

No breaking schema changes

### Key decisions & trade-offs:

- ICS imports are snapshots
- Imported exams fully replace previous ones
- Academic logic over holiday calendars
- Semester phases are derived algorithmically
- No UI-layer deduplication
- All deduplication and cleanup handled at data level

### Concurrency / Data consistency:
- Exam replacement follows a strict sequence: Delete previously imported exams and Insert exams from the new ICS
- User-created tasks are never modified

### Performance considerations:
- Academic week calculation is O(1)
- Class projection filtered in-memory at render time
- No additional Firestore reads during normal navigation

## Checklist:

 Correct class end times from ICS

 Exams imported correctly

 No duplicated events on re-import

 Academic breaks respected

 Classes shown only during teaching weeks

 Week and Month views populated meaningfully

 No UI-level hacks or deduplication

## Notes:

Academic calendar logic is EPFL-specific but extensible

External holiday calendar support can be added later

PlannerRepository semantics remain unchanged

## Issue Reference:

Closes #266

### CODE REVIEW

File: app/src/main/java/com/android/sample/feature/schedule/data/schedule/ScheduleEvent.kt [hunk 1]
```diff
@@ -34,6 +34,16 @@ data class ScheduleEvent(
...
+  val isImportant: Boolean
+    get() =
+        kind in
+            listOf(
+                EventKind.EXAM_FINAL,
+                EventKind.EXAM_MIDTERM,
+                EventKind.SUBMISSION_PROJECT,
+                EventKind.SUBMISSION_MILESTONE,
+                EventKind.SUBMISSION_WEEKLY)
+
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/feature/schedule/data/schedule/ScheduleEvent.kt:46]: Nice addition. Encapsulating the importance logic in a computed property keeps the model expressive and avoids duplicating this logic in the UI layer.

File: app/src/main/java/com/android/sample/feature/schedule/data/schedule/ScheduleEvent.kt [hunk 2]
```diff
@@ -86,3 +96,18 @@ enum class ScheduleTab {
   WEEK,
   MONTH
 }
+
+enum class AcademicWeekType {
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/feature/schedule/data/schedule/ScheduleEvent.kt:100]: This enum is clear and well-scoped. It models academic periods explicitly and avoids relying on implicit or magic values.

File: app/src/main/java/com/android/sample/feature/schedule/repository/schedule/IcsExamImporter.kt [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+                  priority = Priority.HIGH,
+                  sourceTag = SourceTag.Task,
+                  location = ics.location,
+                  categories = ics.categories)
+            }
+
+    scheduleRepository.importEvents(examEvents)
+  }
+
+  private fun mapExamKind(categories: List<String>): EventKind {
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/feature/schedule/repository/schedule/IcsExamImporter.kt:45]: Simple and effective mapping logic. Consolidating categories into a single string makes the keyword matching easy to follow.

File: app/src/main/java/com/android/sample/feature/schedule/repository/schedule/KeywordMatcher.kt [hunk 4]
```diff
@@ -26,4 +26,17 @@ class KeywordMatcher(private val context: Context) {
...
+        when (textOrCategories) {
+          is String -> textOrCategories
+          is List<*> -> textOrCategories.joinToString(" ")
+          else -> ""
+        }.lowercase()
+
+    return listOf("holiday", "vacances", "jour férié", "feries", "noël", "christmas").any {
+      it in all
+    }
+  }
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/feature/schedule/repository/schedule/KeywordMatcher.kt:41]: LGTM

**Review by SamAbd11805 — APPROVED** [review]
Overall, this is a well structured importer. The responsibilities are clearly split between parsing, classification, and persistence, and the code is easy to follow and extend.
