### PR TITLE
 fix(M2): Fixing the bugs that appeared during M2

### LINKED ISSUE #158: Make the screen selection scrollable
**Description:**
As we saw on the meeting at the end of S5, some features are not displayed because the screen is not scrollable, it should be fixed as soon as possible to ensure users have access to all the features.

**Criteria:**

- [x] The screen selection on the left of the homescreen is scrollable
- [x] All features are now accessible from this screen.

### LINKED ISSUE #159: To-do creation fix
**Description:**
Now when attempting to create a to-do, it really creates it and the to-do is displayed on the screen, like when a flashcard is created. It should be possible to create to-dos.

**Criteria:**

- [x] To-do creation works fine on the backend side.
- [x] To-do is displayed after its creation.

### PR DESCRIPTION
**Pull request by alaaae**
### Summary
After the M2, we realised that some bugs slipped into our app. I solved some of them. 
### Checklist
- [x] To-do creation works fine on the backend side.
- [x] To-do is displayed after its creation.
- [x] Add/Edit screens are scrollable
- [x] The screen selection on the left of the homescreen is scrollable
- [x] All features are now accessible from this screen.

closes [#159](https://github.com/EduMonSwent/EduMon/issues/159)
closes [#158](https://github.com/EduMonSwent/EduMon/issues/158)

### CODE REVIEW

File: app/src/main/java/com/android/sample/ui/todo/ToDoForm.kt [hunk 1]
```diff
@@ -72,7 +75,12 @@ fun TodoForm(
             colors = TopAppBarDefaults.topAppBarColors(containerColor = TodoColors.Background))
       }) { padding ->
         Column(
-            Modifier.padding(padding).padding(16.dp).background(TodoColors.Background),
+            modifier =
```
Comment (Adessrrrr) [inline app/src/main/java/com/android/sample/ui/todo/ToDoForm.kt:78]: It's good that we can now scroll inside of the todos.

File: app/src/main/java/com/android/sample/feature/homeScreen/HomeScreen.kt [hunk 2]
```diff
@@ -120,6 +120,7 @@ fun EduMonHomeScreen(
       drawerState = drawerState,
       drawerContent = {
         ModalDrawerSheet(
+            modifier = Modifier.verticalScroll(rememberScrollState()),
```
Comment (Adessrrrr) [inline app/src/main/java/com/android/sample/feature/homeScreen/HomeScreen.kt:123]: It's also good that you made the left panel scrollable.

**Review by Adessrrrr — APPROVED** [review]
Overall this is a small but very useful PR, the 2 main goals of this pull requested are reached, the code behaves as expected now, so we can say that we have 2 bugs fixed.

This PR is now mergeable, as it also passes the quality gate, it's very good.
