### PR TITLE
Feat(schedule): fix today's classes logic

### LINKED ISSUE #243: Fix Today’s Classes Logic
- [x] Filter out classes that have already ended today and correctly display only upcoming ones.
- [x] Fix ICS import to map classes to the correct weekday instead of showing them on the wrong days.
- [x] Make the schedule screen fully scrollable.
- [x] Restore Month View navigation buttons.

### PR DESCRIPTION
**Pull request by KenzaHassayoune**
## Summary:
This PR addresses several usability and logic issues within the Schedule feature. Specifically, it fixes the screen scrolling behavior to ensure headers scroll with the content, corrects the logic for displaying "Today's Classes" to exclude finished classes and correctly map imported ICS events to their specific days, and restores functionality to the Month View navigation buttons.

## What’s in this PR:

**UI/UX Improvements:**
  -   Refactored ScheduleScreen to make the entire screen scrollable (including the header/pet avatar) rather than having a fixed top section.
  -   Fixed Month View navigation: Previous/Next month buttons now correctly update the currentDisplayMonth state.

**Logic & Data Fixes:**
  - Today's Classes Filtering: Updated the ScheduleViewModel logic to filter out classes that have already ended for the current day (based on endTime < LocalTime.now()).
  - ICS Import Logic: Fixed IcsImporter to correctly derive the DayOfWeek from the event's DTSTART date instead of defaulting to Monday or populating all days. This ensures classes only appear on the specific days they are scheduled.

## Implementation Notes:
- Scrolling: Moved the PetHeader and TabRow composables inside the main scrollable Column in ScheduleScreen.kt.
- Data Consistency (ICS Import): The previous IcsImporter implementation had a fallback that often assigned classes to Monday by default. I updated the parsing logic to extract the exact date from the ICS stream and map it to the correct DayOfWeek in the Class entity.
- Performance: The filtering for "past classes" is done efficiently in the ViewModel's state collection pipeline, ensuring the UI only receives the relevant list of upcoming/current classes.

## Testing:
- Updated past tests to adapt to the new changes.

## Notes:
This PR was implemented with the help of ai (chatgpt).

## Issue Reference:
Closes #243

### CODE REVIEW

File: app/src/main/java/com/android/sample/ui/schedule/DayTabContent.kt [hunk 1]
```diff
@@ -77,25 +75,21 @@ fun DayTabContent(
...
-              onClassClick = { vm.onClassClicked(it) },
-              onObjectiveNavigate = onObjectiveNavigation,
-              todos = dayTodos,
-              onTodoClicked = onTodoClicked,
-              allClassesFinished = state.allClassesFinished,
-              modifier = Modifier.fillMaxWidth())
-        }
+  Column(
+      modifier = Modifier.fillMaxSize().padding(bottom = 96.dp),
+      verticalArrangement = Arrangement.spacedBy(16.dp)) {
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/schedule/DayTabContent.kt]: Hardcoded spacing , move to a dimension constant for consistency.

File: app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt [hunk 2]
```diff
@@ -53,105 +51,98 @@ fun MonthTabContent(
...
+      CalendarHeader(
+          title = headerTitle, onPrevClick = onPreviousMonthClick, onNextClick = onNextMonthClick)
+
+      Spacer(Modifier.height(8.dp))
+
+      // ───────────── Card with MonthGrid ─────────────
+      Card(
+          modifier =
+              Modifier.fillMaxWidth()
+                  .shadow(8.dp, RoundedCornerShape(24.dp))
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt]: Hardcoded 24.dp

File: app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt [hunk 3]
```diff
@@ -53,105 +51,98 @@ fun MonthTabContent(
...
+                  .testTag(CalendarScreenTestTags.CALENDAR_CARD),
+          colors = CardDefaults.cardColors(containerColor = DarkBlue.copy(alpha = 0.85f)),
+          shape = RoundedCornerShape(24.dp)) {
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt:74]: same.

File: app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt [hunk 4]
```diff
@@ -53,105 +51,98 @@ fun MonthTabContent(
...
-                              .heightIn(min = 260.dp, max = 420.dp)
-                              .padding(horizontal = 8.dp, vertical = 6.dp)) {
-                        MonthGrid(
-                            currentMonth = currentMonth,
-                            selectedDate = selectedDate,
-                            allTasks = allTasks,
-                            onDateClick = { onDateSelected })
-                      }
+                        .heightIn(min = 260.dp, max = 420.dp)
+                        .padding(horizontal = 8.dp, vertical = 6.dp)) {
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt]: please avoid magic numbers

File: app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt [hunk 5]
```diff
@@ -53,105 +51,98 @@ fun MonthTabContent(
...
-                header = {
-                  Text(
-                      text = stringResource(R.string.schedule_month_important_title),
-                      style =
-                          MaterialTheme.typography.titleMedium.copy(
-                              fontSize = 20.sp, fontWeight = FontWeight.Bold, color = Color.White),
-                      modifier = Modifier.fillMaxWidth().padding(bottom = 14.dp))
-                }) {
-                  val cs = MaterialTheme.colorScheme
+      Spacer(Modifier.height(16.dp))
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/schedule/MonthTabContent.kt]: same here

**Review by SamAbd11805 — CHANGES_REQUESTED** [review]
Overall, the implementation looks clean and consistent. The logic is correct, the state handling is solid, and the composable structure is well-organized.
The only remaining issue is the presence of magic number.

**Review by SamAbd11805 — APPROVED** [review]
LGTM
