### PR TITLE
Fix(Stats): Streak works and stats change according to the current user.

### LINKED ISSUE #265: Fix the stats between accounts on same phone
**Description:**

Currently, when we switch accounts on the same phone, the stats stay the same even if we are no longer on the same account, this should not be the case. Also, the streak is currently not working, so it also needs to be fixed.
In this task you have to fix the streak and to ensure stats are synchronized with the user.

**Criteria:**
- [x] Streak increments correctly
- [x] Stats sync per user account
- [x] 100% unit test coverage
- [x] No race conditions on concurrent updates

### PR DESCRIPTION
**Pull request by Adessrrrr**
## Summary
Fixed the streak counter stuck at 0. Streak now properly increments on daily study and resets after missing days. User stats now synchronized correctly with user accounts, there are not the same stats in the same phone for 2 different users anymore.

## What’s in this PR
- Refactored `addStudyMinutes()` with session type detection (FIRST_EVER, SAME_DAY, CONSECUTIVE_DAY, AFTER_GAP)
- `addReward()` now calls `addStudyMinutes()` internally when minutes > 0
- Field-level Firestore updates in `updateCoins()`, `addPoints()`, `addReward()` to prevent overwriting streak
- User switching detection in `start()` to reset stats when account changes
- `stop()` method for cleanup on logout
- Integrated `start()`/`stop()` calls in `FirebaseAuthRepository`

## Implementation Notes

- **Session Type Logic**: Compares `lastStudyDateEpochDay` with today to determine streak behavior
- **Field-Level Updates**: Using `doc.update()` prevents race conditions from concurrent updates
- **User Account Sync**: Stats repository tracks current UID and resets on account switch
- **Display Rollover**: Separates UI state updates from persistence logic

## Testing

**Unit Tests:**
- All 4 session types (FIRST_EVER, SAME_DAY, CONSECUTIVE_DAY, AFTER_GAP)
- `addReward()` integration with `addStudyMinutes()`
- Field-level updates preventing overwrites
- User switching scenarios
- Authentication flow integration (100% coverage)

**UI / Instrumented Tests:**

- Level-up snackbar appears reliably on CI using testTags (assert by tag, not by text matching alone).
- Snackbar host is composed before triggering events to avoid collector race conditions.
- End-to-end level-up flow: add points → stats update → profile sync → reward event → snackbar rendered.
- Stability under slow devices/CI: test passes without relying on animations or timing assumptions.

## Screenshots / Demos
image

## Checklist

- [x] Streak increments correctly
- [x] Stats sync per user account
- [x] 100% unit test coverage
- [x] No race conditions on concurrent updates

## Notes
Parts of this PR, and parts of the code inside it have been written using an A.I assistant.

## Issue Reference
Closes #265

### CODE REVIEW

File: app/src/main/java/com/android/sample/ui/profile/ProfileViewModel.kt [hunk 1]
```diff
@@ -435,12 +445,18 @@ class ProfileViewModel(
...
       viewModelScope.launch {
         _rewardEvents.emit(event)
-        ToastNotifier.showLevelUpEvent(event)
+
+        // Keep toast gated if you want, but snackbar needs the event always.
+        if (globalSyncCount > Constants.STARTUP_SYNC_THRESHOLD) {
+          ToastNotifier.showLevelUpEvent(event)
+        }
       }
     }
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/profile/ProfileViewModel.kt:461]: LGTM

File: app/src/main/java/com/android/sample/ui/profile/ProfileScreen.kt [hunk 2]
```diff
@@ -651,3 +671,26 @@ fun LevelProgressBar(level: Int, points: Int) {
...
+
+          // Avoid re-showing after recompositions (rewardEvents can be replayed).
+          viewModel.clearRewardEventsReplayCache()
+
+          snackbarHostState.showSnackbar(message)
+        }
+      }
+    }
+  }
+}
```
Comment (SamAbd11805) [inline app/src/main/java/com/android/sample/ui/profile/ProfileScreen.kt:696]: LGTM

**Review by SamAbd11805 — APPROVED** [review]
LGTM

**Review by SamAbd11805 — CHANGES_REQUESTED** [review]
Just fix the two medium Sonar issues and it'll be perfect

**Comment by Adessrrrr** [comment]
> Just fix the two medium Sonar issues and it'll be perfect

I fixed the one with the unused parameter in my latest commit.

For the other one, the coaches explicitly said that when we have this warning with Firestore, we should keep it like this.

@SamAbd11805

**Review by SamAbd11805 — APPROVED** [review]
LGTM
